---
# tasks file for nginx
#- name: Install package with multiple repos enabled
#  yum:
#    name: sos
#    enablerepo: "epel,ol7_latest"

- name: Instalando Epel
  yum:
    name: 'epel-release'
    state: latest
  become: true

- name: Actualizando Respositorios
  yum:
    name: '*'
    state: latest
    exclude: kernel*,foo* 
  become: true

- name: Instalando nginx
  yum:
    name: nginx
    state: latest
  become: true
