---
# tasks file for consul
- name: copiando consul
  copy:
     src: files/consul.tgz
     dest: /usr/sbin/
     mode: 6755
  become: true

- name: descomprimiendo consul
  unarchive:
     src: /usr/sbin/consul.tgz
     dest: /usr/sbin/
     remote_src: yes
     mode: 6755
  become: true

- name: Creando carpeta consul
  file: 
     path: /etc/consul 
     state: directory
  become: true
  
- name: configurando server
  template: 
     src: templates/consul-server.json.j2
     dest: /etc/consul/consul-server.json
  become: true
  when: ansible_hostname == 'manager'

- name: configurando agent
  template: 
     src: templates/consul-agent.json.j2
     dest: /etc/consul/consul-agent.json
  become: true
  when: ansible_hostname != 'manager'

- name: iniciando consul 
  shell: 'consul agent -bootstrap-expect=1 --data-dir /tmp/consul -ui -bind {{ansible_eth1.ipv4.address}} -config-file /etc/consul/consul-server.json &'
  when: ansible_hostname == 'manager'
  become: true

- name: iniciando consul 
  shell: 'consul agent -dev -data-dir /tmp/consul -config-file /etc/consul/consul-agent.json &'
  when: ansible_hostname != 'manager'
  become: true
