---
# tasks file for consul
- name: copiando consul
  copy:
     src: files/consul.tgz
     dest: /usr/sbin/
     mode: 6755
  become: true

- name: descomprimiendo consul
  unarchive:
     src: /usr/sbin/consul.tgz
     dest: /usr/sbin/
     remote_src: yes
     mode: 6755
  become: true

#- name: configurando server
#  template: 
#     src: templates/consul_srv.json.j2
#     dest: /etc/consul/consul.json
#  become: true
#  when: ansible_hostname == 'manager'

#- name: configurando server
#  template: 
#     src: templates/consul_agent.json.j2
#     dest: /etc/consul/consul.json
#  become: true
#  when: ansible_hostname != 'manager'

- name: iniciando consul 
  shell: 'consul agent -server -bootstrap -data-dir /tmp/consul -ui'
  when: ansible_hostname == 'manager'
  become: true

- name: iniciando consul 
  shell: 'consul agent -bootstrap -data-dir /tmp/consul -join 192.168.10.100'
  when: ansible_hostname != 'manager'
  become: true
