stages:
  - provision
  - deploy

# Deploying a new container with the image with latest changes.
provision:stage:
  stage: provision
  environment:
    name: staging
  before_script:
     - vagrant halt
     - vagrant destroy
  script:
     - vagrant up
     - vagrant provision
  only:
    - master
  tags:
    - vagrant
    
    
deploy:stage:
  stage: deploy
  environment:
    name: production
  script:
     - docker stack deploy --compose-file=/vagrant/portainer-stack.yml portainer_stack 
  only:
    - master
  tags:
    - manager-swarm
