stages:
  - clean
  - provision
  - deploy

clean:stage:
  stage: clean
  environment:
    name: staging
  script:
     - ./LimpiezaMaquinasVagrant.sh
  allow_failure: true
  only:
    - master
  tags:
    - vagrant

provision:stage:
  stage: provision
  environment:
    name: staging
  script:
     - vagrant up --no-provision --parallel
     - vagrant provision
  only:
    - master
  tags:
    - vagrant
    
deploy:stage:
  stage: deploy
  environment:
    name: staging
  script:
     - docker stack deploy --compose-file=/vagrant/portainer-stack.yml portainer_stack 
  only:
    - master
  tags:
    - manager-swarm
