---
# tasks file for docker
- name: Instalando prerequisitos docker-repo
  yum:
    name: '{{packages}}'
  become: true
  vars:
    packages:
        - yum-utils
        - device-mapper-persistent-data
        - lvm2

- name: Instalado docker-repo
  shell: "yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo" 
  become: true

- name: Instalando Epel
  yum:
    name: 'epel-release'
    state: latest
  become: true

#- name: Actualizando Respositorios
#  yum:
#    name: '*'
#    state: latest
#    exclude: kernel*,foo* 
#  become: true

- name: Instalando docker
  yum:
    name: docker-ce
    state: latest
  become: true

- name: Subiendo docker...
  service: name=docker state=started
  become: true

- name: "obteniendo docker info"
  shell: docker info
  register: docker_info
  become: true
  changed_when: false

#- include_tasks: creando_swarm.yml
